# Development environment configuration

# Google Cloud settings
google_cloud:
  project_id: "finflow-hackathon"
  credentials_path: "/Users/dhairyagundechia/.config/gcloud/application_default_credentials.json"