# Production environment configuration

# Google Cloud settings
google_cloud:
  project_id: finflow-hackathon
  region: us-central1
  
# Storage settings
storage:
  bucket_name: finflow-prod-data
  
# Document AI settings
document_ai:
  processor_location: us
  form_processor_id: YOUR_FORM_PROCESSOR_ID  # Replace later

# Vertex AI settings
vertex_ai:
  model_name: text-bison
  temperature: 0.0
  max_output_tokens: 1024
  
# Application settings
app:
  debug: false
  log_level: WARNING
