# Production environment configuration

# Google Cloud settings
google_cloud:
  project_id: finflow-production
  region: us-central1
  location: us-central1
  
  # Document AI settings
  document_ai:
    processor_id: processor_id_placeholder
    
  # BigQuery settings
  bigquery:
    dataset_id: finflow_prod
    
  # Cloud Storage settings
  storage:
    bucket_name: finflow-prod-documents

# Agent settings
agents:
  master_orchestrator:
    model: gemini-2.0-pro
    temperature: 0.2
    
  document_processor:
    model: gemini-2.0-flash
    temperature: 0.1
    
  validation:
    model: gemini-2.0-pro
    temperature: 0.1
    
  rule_retrieval:
    model: gemini-2.0-flash
    temperature: 0.1
    
  storage:
    model: gemini-2.0-flash
    temperature: 0.1
    
  analytics:
    model: gemini-2.0-pro
    temperature: 0.2

# Logging settings
logging:
  level: WARNING
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  
# Storage settings
storage:
  bucket_name: finflow-prod-data
  
# Document AI settings
document_ai:
  processor_location: us
  form_processor_id: YOUR_FORM_PROCESSOR_ID  # Replace later

# Vertex AI settings
vertex_ai:
  model_name: text-bison
  temperature: 0.0
  max_output_tokens: 1024
  
# Application settings
app:
  debug: false
  log_level: WARNING
